export const beats = [
  {
    title: "Woman",
    path: "/audio/beat1.mp3",
    cover: "/cover/woman.png",
    genre: ["hipHop"],
    // genreText: ["Hip Hop"]
    bpm: 90,
  },
  {
    title: "Sunny Express",
    path: "/audio/beat2.mp3",
    cover: "/cover/sunnyexpress.png",
    genre: ["hipHop"],
    bpm: 128,
  },
  {
    title: "Where You Wanna?",
    path: "/audio/beat15.mp3",
    cover: "/cover/whereyouwanna.jpeg",
    genre: ["edm"],
    bpm: 124,
  },
  {
    title: "Soul Saver",
    path: "/audio/beat16.mp3",
    cover: "/cover/soulsaver.jpg",
    genre: ["hipHop"],
    bpm: 86,
  },
  {
    title: "DK",
    path: "/audio/beat3.mp3",
    cover: "/cover/dk.jpg",
    genre: ["hipHop"],
    bpm: 130,
  },
  {
    title: "Insanity",
    path: "/audio/beat17.mp3",
    cover: "/cover/insanity.png",
    genre: ["pop"],
    bpm: 136,
  },
  {
    title: "Masterpiece",
    path: "/audio/beat18.mp3",
    cover: "/cover/masterpiece.jpg",
    genre: ["hipHop"],
    bpm: 120,
  },
  {
    title: "Choppy",
    path: "/audio/beat19.mp3",
    cover: "/cover/choppy.jpg",
    genre: ["hipHop"],
    bpm: 88,
  },
  {
    title: "You Dig",
    path: "/audio/beat4.mp3",
    cover: "/cover/youdig.png",
    genre: ["hipHop"],
    bpm: 94,
  },
  {
    title: "I Can't Take It",
    path: "/audio/beat11.mp3",
    cover: "/cover/icanttakeit.jpg",
    genre: ["pop", "edm"],
    bpm: 120,
  },
  {
    title: "Ill Intent",
    path: "/audio/beat5.mp3",
    cover: "/cover/illintent.png",
    genre: ["hipHop"],
    bpm: 78,
  },
  {
    title: "The Chase",
    path: "/audio/beat6.mp3",
    cover: "/cover/thechase.png",
    genre: ["hipHop"],
    bpm: 120,
  },
  {
    title: "Trees",
    path: "/audio/beat7.mp3",
    cover: "/cover/trees.jpg",
    genre: ["hipHop"],
    bpm: 88,
  },
  {
    title: "Enough of Pain",
    path: "/audio/beat12.mp3",
    cover: "/cover/enoughofpain.png",
    genre: ["edm"],
    bpm: 123,
  },
  {
    title: "Pray to God",
    path: "/audio/beat8.mp3",
    cover: "/cover/praytogod.jpg",
    genre: ["hipHop"],
    bpm: 98,
  },
  {
    title: "Tokyo Bound",
    path: "/audio/beat9.mp3",
    cover: "/cover/tokyobound.jpg",
    genre: ["hipHop"],
    bpm: 136,
  },
  {
    title: "Coming After You",
    path: "/audio/beat13.mp3",
    cover: "/cover/comingafteryou.jpeg",
    genre: ["pop", "edm"],
    bpm: 120,
  },
  {
    title: "Drive at Night",
    path: "/audio/beat20.mp3",
    cover: "/cover/driveatnight.jpg",
    genre: ["hipHop"],
    bpm: 133,
  },
  {
    title: "No Fan of Me",
    path: "/audio/beat14.mp3",
    cover: "/cover/nofanofme.jpg",
    genre: ["pop"],
    bpm: 112,
  },
  {
    title: "Clint Eastwood",
    path: "/audio/beat10.mp3",
    cover: "/cover/clinteastwood.png",
    genre: ["hipHop"],
    bpm: 90,
  },
];

export default beats