export const beats = [
  {
    title: "Woman",
    path: "/audio/beat1.mp3",
    cover: "/cover/sunnyexpress.png",
    genre: ["Hip Hop"],
    bpm: 128,
  },
  {
    title: "Sunny Express",
    path: "/audio/beat2.mp3",
    cover: "/cover/sunnyexpress.png",
    genre: ["Hip Hop"],
    bpm: 128,
  },
  {
    title: "DK",
    path: "/audio/beat3.mp3",
    cover: "/cover/youdig.png",
    genre: ["Hip Hop", "Phonk"],
    bpm: 94,
  },
  {
    title: "You Dig",
    path: "/audio/beat4.mp3",
    cover: "/cover/youdig.png",
    genre: ["Hip Hop"],
    bpm: 94,
  },
  {
    title: "Ill Intent",
    path: "/audio/beat5.mp3",
    cover: "/cover/illintent.png",
    genre: ["Hip Hop"],
    bpm: 78,
  },
  {
    title: "The Chase",
    path: "/audio/beat6.mp3",
    cover: "/cover/thechase.png",
    genre: ["Hip Hop", "Phonk"],
    bpm: 120,
  },
  {
    title: "Trees",
    path: "/audio/beat7.mp3",
    cover: "/cover/thechase.png",
    genre: ["Hip Hop", "Psychedelic"],
    bpm: 120,
  },
  {
    title: "Tokyo Bound",
    path: "/audio/beat9.mp3",
    cover: "/cover/clinteastwood.png",
    genre: ["Hip Hop", "Phonk"],
    bpm: 90,
  },
  {
    title: "Clint Eastwood",
    path: "/audio/beat10.mp3",
    cover: "/cover/clinteastwood.png",
    genre: ["Hip Hop"],
    bpm: 90,
  },
];
